language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.1
  - build-tools-26.0.2
  - android-27
  - android-26
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - android-sdk-license-.+
  - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew --daemon build jacocoTestReportDebug --info

after_success:
   - bash <(curl -s https://codecov.io/bash)